
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwmaxhltdtksnwbrpdxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3bWF4aGx0ZHRrc253YnJwZHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjIwMjMsImV4cCI6MjA2Mjk5ODAyM30.h4I9UeTtZ0dXs9-QyeIIG1b0qwuZWGBDewgvtgwbG1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});
